#!/bin/bash

echo "🔍 Finding correct App Store Connect Issuer ID"
echo ""
echo "❌ Current Issue: Using Apple ID instead of Issuer ID"
echo "   Current value: 6751101564 (this is your Apple ID)"
echo "   Expected format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (UUID)"
echo ""
echo "📋 How to find your Issuer ID:"
echo ""
echo "1. 🌐 Go to: https://appstoreconnect.apple.com/access/api"
echo "2. 📋 Look for 'Issuer ID' at the top of the page"
echo "3. 📋 It should look like: 12345678-1234-1234-1234-123456789012"
echo "4. 📝 Copy that UUID and update your configuration"
echo ""
echo "🔧 Quick fix options:"
echo ""
echo "Option 1 - Update apple.id file:"
echo "   echo 'YOUR_ISSUER_ID_UUID_HERE' > apple.id"
echo ""
echo "Option 2 - Create issuer.id file:"
echo "   echo 'YOUR_ISSUER_ID_UUID_HERE' > issuer.id"
echo ""
echo "📋 Common Issuer ID patterns:"
echo "   - Always 36 characters long (including dashes)"
echo "   - Format: 8-4-4-4-12 characters"
echo "   - Example: 69a6de7f-5678-47e3-e053-5b8c7c11a4d1"
echo ""
echo "🚨 This is the most likely cause of authentication failures!"
echo ""

# Test if we can find any UUID-like patterns in existing files
echo "🔍 Searching for UUID patterns in existing files..."
grep -r -E "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" . 2>/dev/null | head -5 || echo "   No UUID patterns found in current files"

echo ""
echo "✅ Once you have the correct Issuer ID, the upload should work!" 