name: Build and Deploy iOS to App Store

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Add iOS platform
      run: |
        npm install @capacitor/ios
        npx cap add ios
    
    - name: Sync Capacitor
      run: npx cap sync
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    
    - name: Build iOS app
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination generic/platform=iOS -archivePath App.xcarchive archive
        xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
      env:
        DEVELOPER_APP_ID: ${{ secrets.APPLE_TEAM_ID }}
    
    - name: Upload to App Store Connect
      uses: apple-actions/upload-testflight@v1
      with:
        app-path: ios/App/App.ipa
        api-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        api-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        skip-waiting-for-processing: true
    
    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-store-ipa
        path: ios/App/App.ipa
        retention-days: 30
