name: Build and Deploy iOS to App Store

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger
  release:
    types: [published]  # Triggers when a release is published

env:
  NODE_VERSION: '18'
  XCODE_VERSION: '15.2'

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper versioning
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g @capacitor/cli
    
    - name: Setup iOS platform
      run: |
        # Remove existing iOS platform if incomplete
        if [ -d "ios" ] && [ ! -f "ios/App/Podfile" ]; then
          echo "Removing incomplete iOS platform..."
          rm -rf ios
        fi
        
        # Add iOS platform if it doesn't exist
        if [ ! -d "ios/App/App.xcworkspace" ]; then
          echo "Adding iOS platform..."
          npx cap add ios
        fi
    
    - name: Sync Capacitor
      run: npx cap sync ios
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install --repo-update
    
    - name: Configure iOS build settings
      run: |
        cd ios/App
        # Update bundle identifier and team ID
        /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.qaonline.app" App/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName QA-Online" App/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{ github.ref_name == 'main' && '1.0.0' || github.ref_name }}" App/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" App/Info.plist
    
    - name: Build iOS app
      run: |
        cd ios/App
        # Clean previous builds
        xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release
        
        # Build archive
        xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          CODE_SIGN_IDENTITY="iPhone Distribution" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM="${{ secrets.APPLE_TEAM_ID }}" \
          PRODUCT_BUNDLE_IDENTIFIER="com.qaonline.app"
        
        # Export IPA
        xcodebuild -exportArchive \
          -archivePath App.xcarchive \
          -exportPath . \
          -exportOptionsPlist exportOptions.plist \
          -allowProvisioningUpdates
    
    - name: Verify IPA file
      run: |
        cd ios/App
        if [ ! -f "App.ipa" ]; then
          echo "❌ IPA file was not created!"
          exit 1
        fi
        echo "✅ IPA file created successfully"
        ls -la App.ipa
    
    - name: Upload to App Store Connect
      uses: apple-actions/upload-testflight@v1
      with:
        app-path: ios/App/App.ipa
        api-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        api-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        skip-waiting-for-processing: true
        skip-metadata-upload: true
        skip-screenshots: true
    
    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-store-ipa-${{ github.run_number }}
        path: ios/App/App.ipa
        retention-days: 90
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: QA-Online iOS App ${{ github.ref_name }}
        body: |
          ## QA-Online iOS App Release ${{ github.ref_name }}
          
          ### What's New
          - iOS app build for App Store distribution
          - Automated build and deployment
          
          ### Build Information
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          
          ### Installation
          Download the IPA file from the artifacts or install from TestFlight.
        draft: false
        prerelease: false
    
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✅ iOS build completed successfully!
          
          **Build Information:**
          - Build Number: ${context.runNumber}
          - IPA: Available as artifact
          - Status: Ready for App Store Connect`
          })
